---
name: Tests
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: "The key to record the code coverage to CodeCov"
        required: true

jobs:
  tests:
    name: Rust Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Update Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Add LLVM tools
        run: rustup component add llvm-tools-preview

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Cinstrument-coverage"
          RUSTDOCFLAGS: "-Cinstrument-coverage"

      - name: Install grcov
        run: cargo install grcov

      - name: Generate coverage report
        run: grcov . --binary-path target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../**' --ignore '/*' -o coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e # v5
        with:
          files: ./coverage.lcov
          flags: rust
          token: ${{ secrets.CODECOV_TOKEN }}
